# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 06:57
from __future__ import unicode_literals

import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
                ('article', models.TextField(verbose_name='文章')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('img', models.ImageField(upload_to=article.models.upload_to_goods_img, verbose_name='图片')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
