# Generated by Django 2.0 on 2018-12-14 02:39

import DjangoUeditor.models
import article.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('description', models.CharField(max_length=256, verbose_name='描述')),
                ('article', DjangoUeditor.models.UEditorField(default='', verbose_name='内容详情')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('status', models.IntegerField(choices=[(0, '显示'), (1, '禁用')], verbose_name='状态')),
                ('title_img', models.ImageField(blank=True, null=True, upload_to=article.models.upload_to_goods_img, verbose_name='图片')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('status', models.IntegerField(choices=[(0, '启用'), (1, '关闭')], verbose_name='状态')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
